Added content about deployment modes
neo4j/neo4j-browser pull request #1357
Opened 2021-04-13 07:12 UTC by martin-neotech

Improved deployment modes content.
Dedicated web server documentation.

2021-04-13 11:25 UTC, renetapopova requested changes
Thanks @martin-neotech! Really valuable content! See my suggestions inline.

2021-04-13 11:25 UTC, renetapopova commented on docs/modules/ROOT/pages/deployment-modes.adoc
> +Point your web browser to `http://localhost:8080`.
Again the link formatting. We have to decide how we format the links and make the documentation consistent.

2021-04-13 11:25 UTC, renetapopova commented on docs/modules/ROOT/pages/deployment-modes.adoc
> +**4. Test connecting to a Neo4j database instance.**
```suggestion
. Test the connection to a Neo4j database instance.
```

2021-04-13 11:25 UTC, renetapopova commented on docs/modules/ROOT/pages/deployment-modes.adoc
> +Start a Neo4j database instance to test for connection.
```suggestion

```

2021-04-13 11:25 UTC, renetapopova commented on docs/modules/ROOT/pages/deployment-modes.adoc
> +If you have the Neo4j tarball you can start the database instance with the command (assuming that the CWD is _<neo4j-home>_):
```suggestion
+
If you have the Neo4j tarball, you can start a database instance with the following command (assuming that the CWD is _<neo4j-home>_):
```
What does "CWD" stand for?

2021-04-13 11:25 UTC, renetapopova commented on docs/modules/ROOT/pages/deployment-modes.adoc
> +In Neo4j Browser connect to the Neo4j database instance with the URI:
```suggestion
In Neo4j Browser, connect to the Neo4j database instance with the  Neo4j Browser URI:
```

2021-04-13 11:25 UTC, renetapopova commented on docs/modules/ROOT/pages/deployment-modes.adoc
> +See xref:operations#create-dbms-connection[Create a DBMS connection] for more details how to setup a connection to Neo4j in Neo4j Browser.
```suggestion
For details on how to set up a connection to Neo4j in Neo4j Browser, see xref:operations#create-dbms-connection[Create a DBMS connection].
```

2021-04-13 11:25 UTC, renetapopova commented on docs/modules/ROOT/pages/deployment-modes.adoc
> +=== Build and run web server
```suggestion
[[build-web-server]]
=== Build and run a web server
```

2021-04-13 11:25 UTC, renetapopova commented on docs/modules/ROOT/pages/deployment-modes.adoc
> +.Build and run web server
```suggestion
.Build and run a web server
```

2021-04-13 11:25 UTC, renetapopova commented on docs/modules/ROOT/pages/deployment-modes.adoc
> +The command will only get the `master` branch to save bandwidth and file space.
```suggestion
The command gets only the `master` branch to save bandwidth and file space.
```

2021-04-13 11:25 UTC, renetapopova commented on docs/modules/ROOT/pages/deployment-modes.adoc
> +Change the current working directory to the root of the git repository.
```suggestion
.. Change the current working directory to the root of the Git repository.
```

2021-04-13 11:25 UTC, renetapopova commented on docs/modules/ROOT/pages/deployment-modes.adoc
> +**1. Download Neo4j Browser.**
```suggestion
. Download Neo4j Browser from Maven.
```

2021-04-13 11:25 UTC, renetapopova commented on docs/modules/ROOT/pages/deployment-modes.adoc
> +Download Neo4j Browser from Maven:
```suggestion

```

2021-04-13 11:25 UTC, renetapopova commented on docs/modules/ROOT/pages/deployment-modes.adoc
> +Or manually go to link:https://search.maven.org/artifact/org.neo4j.client/neo4j-browser[`https://search.maven.org/artifact/org.neo4j.client/neo4j-browser`] and download Neo4j Browser.
```suggestion
Alternatively, go to link:https://search.maven.org/artifact/org.neo4j.client/neo4j-browser[`https://search.maven.org/artifact/org.neo4j.client/neo4j-browser`] and download Neo4j Browser.
```

2021-04-13 11:25 UTC, renetapopova commented on docs/modules/ROOT/pages/deployment-modes.adoc
> +**2. Unzip the .jar file.**
```suggestion
. Unzip the .jar file.
```

2021-04-13 11:25 UTC, renetapopova commented on docs/modules/ROOT/pages/deployment-modes.adoc
> +Unzip the `.jar` file:
```suggestion

```

2021-04-13 11:25 UTC, renetapopova commented on docs/modules/ROOT/pages/deployment-modes.adoc
> +
```suggestion
+
```

2021-04-13 11:25 UTC, renetapopova commented on docs/modules/ROOT/pages/deployment-modes.adoc
> +
```suggestion
+
```

2021-04-13 11:25 UTC, renetapopova commented on docs/modules/ROOT/pages/deployment-modes.adoc
> +
```suggestion
+
```

2021-04-13 11:25 UTC, renetapopova commented on docs/modules/ROOT/pages/deployment-modes.adoc
> +**3. Host web application with a HTTP server.**
```suggestion
. Host a web application with an HTTP server.
```

2021-04-13 11:25 UTC, renetapopova commented on docs/modules/ROOT/pages/deployment-modes.adoc
> +
```suggestion
+
```

2021-04-13 11:25 UTC, renetapopova commented on docs/modules/ROOT/pages/deployment-modes.adoc
> +
```suggestion
+
```

2021-04-13 11:25 UTC, renetapopova commented on docs/modules/ROOT/pages/deployment-modes.adoc
> +
```suggestion
+
```

2021-04-13 11:25 UTC, renetapopova commented on docs/modules/ROOT/pages/deployment-modes.adoc
> +Point your web browser to `http://localhost:8080`.
```suggestion
.. Point your web browser to `http://localhost:8080`.
```

2021-04-13 11:25 UTC, renetapopova commented on docs/modules/ROOT/pages/deployment-modes.adoc
> +
```suggestion
+
```

2021-04-13 11:25 UTC, renetapopova commented on docs/modules/ROOT/pages/deployment-modes.adoc
> +
```suggestion
+
```

2021-04-13 11:25 UTC, renetapopova commented on docs/modules/ROOT/pages/deployment-modes.adoc
> +
```suggestion
+
```

2021-04-13 11:25 UTC, renetapopova commented on docs/modules/ROOT/pages/deployment-modes.adoc
> +**1. Get the source code.**
```suggestion
. Get the source code.
```

2021-04-13 11:25 UTC, renetapopova commented on docs/modules/ROOT/pages/deployment-modes.adoc
> +
```suggestion
+
```

2021-04-13 11:25 UTC, renetapopova commented on docs/modules/ROOT/pages/deployment-modes.adoc
> +Clone the Neo4j Browser git repository.
```suggestion
.. Clone the Neo4j Browser Git repository. +
```

2021-04-13 11:25 UTC, renetapopova commented on docs/modules/ROOT/pages/deployment-modes.adoc
> +
```suggestion
+
```

2021-04-13 11:25 UTC, renetapopova commented on docs/modules/ROOT/pages/deployment-modes.adoc
> +
```suggestion
+
```

2021-04-13 11:25 UTC, renetapopova commented on docs/modules/ROOT/pages/deployment-modes.adoc
> +**2. Build with Node.js**
```suggestion
. Build with Node.js.
```

2021-04-13 11:25 UTC, renetapopova commented on docs/modules/ROOT/pages/deployment-modes.adoc
> +
```suggestion
+
```

2021-04-13 11:25 UTC, renetapopova commented on docs/modules/ROOT/pages/deployment-modes.adoc
> +Install Node.js dependencies:
```suggestion
.. Install Node.js dependencies:
```

2021-04-13 11:25 UTC, renetapopova commented on docs/modules/ROOT/pages/deployment-modes.adoc
> +
```suggestion
+
```

2021-04-13 11:25 UTC, renetapopova commented on docs/modules/ROOT/pages/deployment-modes.adoc
> +Build the project:
```suggestion
.. Build the project.
```

2021-04-13 11:25 UTC, renetapopova commented on docs/modules/ROOT/pages/deployment-modes.adoc
> +
```suggestion
+
```

2021-04-13 11:25 UTC, renetapopova commented on docs/modules/ROOT/pages/deployment-modes.adoc
> +**3. Host web application with a HTTP server.**
```suggestion
. Host web application with an HTTP server.
```

2021-04-13 11:25 UTC, renetapopova commented on docs/modules/ROOT/pages/deployment-modes.adoc
> +
```suggestion
+
```

2021-04-13 11:25 UTC, renetapopova commented on docs/modules/ROOT/pages/deployment-modes.adoc
> +Start a web server (in this example you will start a web server with Python 3) to serve the content:
```suggestion
.. Start a web server to serve the content.
In this example, you start a web server with Python 3.
```

2021-04-13 11:25 UTC, renetapopova commented on docs/modules/ROOT/pages/deployment-modes.adoc
> +
```suggestion
+
```

2021-04-13 11:25 UTC, renetapopova commented on docs/modules/ROOT/pages/deployment-modes.adoc
> +
```suggestion
+
```

2021-04-13 11:25 UTC, renetapopova commented on docs/modules/ROOT/pages/deployment-modes.adoc
> +Point your web browser to `http://localhost:8080`.
```suggestion
.. Point your web browser to `http://localhost:8080`.
```

2021-04-13 11:25 UTC, renetapopova commented on docs/modules/ROOT/pages/deployment-modes.adoc
> +
```suggestion
+
```

2021-04-13 11:25 UTC, renetapopova commented on docs/modules/ROOT/pages/deployment-modes.adoc
> +See xref:operations#create-dbms-connection[Create a DBMS connection] for details how to setup a connection to Neo4j in Neo4j Browser.
```suggestion
For details on how to set up a connection to Neo4j in Neo4j Browser, see xref:operations#create-dbms-connection[Create a DBMS connection].
```

2021-04-14 08:13 UTC, martin-neotech commented on docs/modules/ROOT/pages/deployment-modes.adoc
> +If you have the Neo4j tarball you can start the database instance with the command (assuming that the CWD is _<neo4j-home>_):
current working directory

2021-04-19 13:09 UTC, renetapopova requested changes
Looks much better. Some minor suggestions and typos.

2021-04-19 13:09 UTC, renetapopova commented on docs/modules/ROOT/pages/deployment-modes.adoc
> +Neo4j Browser is open source (GNU General Public License v3.0) and the source code can be found at link:https://github.com/neo4j/neo4j-browser[_https://github.com/neo4j/neo4j-browser_].
```suggestion
Neo4j Browser is open source (GNU General Public License v3.0), and the source code can be found at link:https://github.com/neo4j/neo4j-browser[_https://github.com/neo4j/neo4j-browser_].
```

2021-04-19 13:09 UTC, renetapopova commented on docs/modules/ROOT/pages/deployment-modes.adoc
> +If you want to extend or contribute to the project you can alter the code.
```suggestion
If you want to extend or contribute to the project, you can alter the code.
```

2021-04-19 13:09 UTC, renetapopova commented on docs/modules/ROOT/pages/deployment-modes.adoc
> +This allows you to run an altered version of Neo4j Browser.
```suggestion
This allows you to run a modified version of Neo4j Browser.
```

2021-04-19 13:09 UTC, renetapopova commented on docs/modules/ROOT/pages/deployment-modes.adoc
> +A simple HTTP server that is ideal for serving a static site, single page application or just a static file.
```suggestion
A simple HTTP server is ideal for serving a static site, single page application, or just a static file.
```

2021-04-19 13:09 UTC, renetapopova commented on docs/modules/ROOT/pages/deployment-modes.adoc
> +[[pre-build-neo4j-browser]]
```suggestion
[[pre-built-neo4j-browser]]
```

2021-04-19 13:09 UTC, renetapopova commented on docs/modules/ROOT/pages/deployment-modes.adoc
> +=== Pre-build Neo4j Browser
```suggestion
=== Pre-built Neo4j Browser
```

2021-04-19 13:09 UTC, renetapopova commented on docs/modules/ROOT/pages/deployment-modes.adoc
> +.Get pre-build Neo4j Browser and run an HTTP web server
```suggestion
.Get pre-built Neo4j Browser and run an HTTP web server
```

2021-04-19 13:09 UTC, renetapopova commented on docs/modules/ROOT/pages/deployment-modes.adoc
> +In this example you start a web server with Python 3.
```suggestion
In this example, you start a web server with Python 3.
```

2021-04-19 13:09 UTC, renetapopova commented on docs/modules/ROOT/pages/deployment-modes.adoc
> +If you have the Neo4j tarball you can start the database instance with the command (assuming that the current working directory is _<neo4j-home>_):
```suggestion
If you have the Neo4j tarball, you can start the database instance with the command (assuming that the current working directory is _<neo4j-home>_):
```

2021-04-21 07:38 UTC, renetapopova approved these changes
LGTM, thanks @martin-neotech

2021-04-21 09:33 UTC, merged