Align documentation by allowing Graph export in JSON & CSV format
neo4j/neo4j-browser pull request #1939
Opened 2023-09-21 05:05 UTC by QubitPi

This PR aligns graph export behavior with [what's being documented](https://neo4j.com/docs/browser-manual/current/operations/export-results/), i.e. exporting in JSON and CSV

![Uploading page.png…]()

2023-09-21 05:12 UTC, QubitPi commented
Hi Neo4J team, I have also signed the CLA (jack20220723@gmail.com). Please let me know if I can help with anything else

2023-09-21 07:41 UTC, OskarDamkjaer commented
Hi @QubitPi and thanks for opening this PR! I think it is a good change and I'll have a look at the code now 


I put your name in system now, so the CLA check should be green on when re-run :+1:

2023-09-21 07:46 UTC, OskarDamkjaer requested changes

2023-09-21 07:46 UTC, OskarDamkjaer commented on src/browser/modules/Stream/CypherFrame/CypherFrame.tsx
>      const downloadGraphics = [
This list is meant for the graphical / image downloads and I would like to keep this list with only those two items. To solve the problem of showing the text downloads I think it's better if you extend the `textDownloadEnabled` to say that text download is enabled for when the visualization is open too!

```ts
    const textDownloadEnabled = () =>
      this.getRecords().length > 0 &&
      this.state.openView &&
      [ViewTypes.TEXT, ViewTypes.TABLE, ViewTypes.CODE, ViewTypes.VISUALIZATION].includes(
        this.state.openView
      )
```

I think that should do the trick :)

2023-09-22 01:52 UTC, QubitPi commented
Hi @OskarDamkjaer, thank you very much for the quick feedback. Your comment makes sense and I have change it accordingly

2023-09-22 10:50 UTC, OskarDamkjaer approved these changes
Looks good, thanks! I'll merge when we get the tests to pass 💯

2023-09-22 14:41 UTC, merged